clc;
close all;
clear all;

getQuadrotorDynamicsAndJacobian;

nx = 12;
ny = 12;
nu = 4;
nlmpcobj = nlmpc(nx, ny, nu);

nlmpcobj.Model.StateFcn = "QuadrotorStateFcn";
nlmpcobj.Jacobian.StateFcn = @QuadrotorStateJacobianFcn;
rng(0)

validateFcns(nlmpcobj,rand(nx,1),rand(nu,1));

Ts = 0.1;
p = 18;
m = 2;
nlmpcobj.Ts = Ts;
nlmpcobj.PredictionHorizon = p;
nlmpcobj.ControlHorizon = m;

nlmpcobj.MV = struct( ...
    Min={0;0;0;0}, ...
    Max={10;10;10;10}, ...
    RateMin={-2;-2;-2;-2}, ...
    RateMax={2;2;2;2} ...
    );

nlmpcobj.Weights.OutputVariables = [1 1 1 1 1 1 0 0 0 0 0 0];

nlmpcobj.Weights.ManipulatedVariables = [0.1 0.1 0.1 0.1];

nlmpcobj.Weights.ManipulatedVariablesRate = [0.1 0.1 0.1 0.1];


% Specify the initial conditions
x = [3;3;3;0;0;0;0;0;0;0;0;0];

% Nominal control target (average to keep quadrotor floating)
nloptions = nlmpcmoveopt;
nloptions.MVTarget = [4.9 4.9 4.9 4.9]; 
mv = nloptions.MVTarget;
%%
% Simulation duration in seconds
Duration = 20;

% Display waitbar to show simulation progress
%hbar = waitbar(0,"Simulation Progress");

% MV last value is part of the controller state
lastMV = mv;

% Store states for plotting purposes
xHistory = x';
uHistory = lastMV;
time = linspace(0,Duration,(Duration/Ts)+1);
% Simulation loop
for k = 1:(Duration/Ts)
    
    % Set references for previewing
    t = linspace(k*Ts, (k+p-1)*Ts,p);
    fprintf("\nProgress: %d %% \n",round(((t(end)/Duration)-0.09)*100))
    yref = QuadrotorReferenceTrajectory(t);

    % Compute control move with reference previewing
    xk = xHistory(k,:);
    [uk,nloptions,info] = nlmpcmove(nlmpcobj,xk,lastMV,yref',[],nloptions);

    % Store control move
    uHistory(k+1,:) = uk';
    lastMV = uk;

    % Simulate quadrotor for the next control interval (MVs = uk) 
    ODEFUN = @(t,xk) QuadrotorStateFcn(xk,uk);
    [TOUT,XOUT] = ode45(ODEFUN,[0 Ts], xHistory(k,:)');

    % Update quadrotor state
    xHistory(k+1,:) = XOUT(end,:);

    % Update waitbar
    %waitbar(k*Ts/Duration,hbar);
end

% Close waitbar 
%close(hbar)

animateQuadrotorTrajectory;
% 
% 
% 
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         x_dot_t
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         y_dot_t
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         z_dot_t
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       phi_dot_t
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     theta_dot_t
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       psi_dot_t
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (k*(sin(phi(t))*sin(psi(t)) + cos(phi(t))*cos(psi(t))*sin(theta(t)))*(u1 + u2 + u3 + u4))/m
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -(k*(cos(psi(t))*sin(phi(t)) - cos(phi(t))*sin(psi(t))*sin(theta(t)))*(u1 + u2 + u3 + u4))/m
%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         (k*cos(phi(t))*cos(theta(t))*(u1 + u2 + u3 + u4))/m - g
% ((theta_dot_t*((psi_dot_t*(Iyy*cos(phi_t)^2*cos(theta_t) - Izz*cos(phi_t)^2*cos(theta_t) - Iyy*cos(theta_t)*sin(phi_t)^2 + Izz*cos(theta_t)*sin(phi_t)^2))/2 - (theta_dot_t*(2*Iyy*cos(phi_t)*sin(phi_t) - 2*Izz*cos(phi_t)*sin(phi_t)))/2) + psi_dot_t*((theta_dot_t*(Iyy*cos(phi_t)^2*cos(theta_t) - Izz*cos(phi_t)^2*cos(theta_t) - Iyy*cos(theta_t)*sin(phi_t)^2 + Izz*cos(theta_t)*sin(phi_t)^2))/2 + (psi_dot_t*(2*Iyy*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Izz*cos(phi_t)*cos(theta_t)^2*sin(phi_t)))/2 + Ixx*theta_dot_t*cos(theta_t)) - k*l*(u2 - u4))*(Iyy*Izz*cos(phi(t))^4*cos(theta(t))^2 + Ixx*Iyy*cos(phi(t))^2*sin(theta(t))^2 + Iyy*Izz*cos(theta(t))^2*sin(phi(t))^4 + Ixx*Izz*sin(phi(t))^2*sin(theta(t))^2 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))^2*sin(phi(t))^2))/(Ixx*Iyy*Izz*cos(phi(t))^4*cos(theta(t))^2 + Ixx*Iyy*Izz*cos(theta(t))^2*sin(phi(t))^4 + 2*Ixx*Iyy*Izz*cos(phi(t))^2*cos(theta(t))^2*sin(phi(t))^2) + (sin(theta(t))*(Iyy*cos(phi(t))*sin(phi(t)) - Izz*cos(phi(t))*sin(phi(t)))*(theta_dot_t*((psi_dot_t*(Iyy*cos(phi_t)*sin(phi_t)*sin(theta_t) - Izz*cos(phi_t)*sin(phi_t)*sin(theta_t)))/2 - 2*Iyy*phi_dot_t*cos(phi_t)*sin(phi_t) + 2*Izz*phi_dot_t*cos(phi_t)*sin(phi_t)) + psi_dot_t*((theta_dot_t*(Iyy*cos(phi_t)*sin(phi_t)*sin(theta_t) - Izz*cos(phi_t)*sin(phi_t)*sin(theta_t)))/2 + (psi_dot_t*(2*Izz*cos(phi_t)^2*cos(theta_t)*sin(theta_t) - 2*Ixx*cos(theta_t)*sin(theta_t) + 2*Iyy*cos(theta_t)*sin(phi_t)^2*sin(theta_t)))/2 + (Ixx*phi_dot_t*cos(theta_t))/2 + Iyy*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Izz*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Iyy*phi_dot_t*cos(theta_t)*sin(phi_t)^2 + Izz*phi_dot_t*cos(theta_t)*sin(phi_t)^2 - Iyy*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t) + Izz*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t)) + k*l*(u1 - u3) + (Ixx*phi_dot_t*psi_dot_t*cos(theta_t))/2))/(Iyy*Izz*cos(phi(t))^4*cos(theta(t)) + Iyy*Izz*cos(theta(t))*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))*sin(phi(t))^2) + (sin(theta(t))*(Iyy*cos(phi(t))^2 + Izz*sin(phi(t))^2)*(psi_dot_t*(2*Izz*phi_dot_t*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Iyy*phi_dot_t*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Ixx*theta_dot_t*cos(theta_t)*sin(theta_t) + 2*Izz*theta_dot_t*cos(phi_t)^2*cos(theta_t)*sin(theta_t) + 2*Iyy*theta_dot_t*cos(theta_t)*sin(phi_t)^2*sin(theta_t)) - theta_dot_t*(Iyy*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Izz*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Iyy*phi_dot_t*cos(theta_t)*sin(phi_t)^2 + Izz*phi_dot_t*cos(theta_t)*sin(phi_t)^2 - Iyy*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t) + Izz*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t)) - b*(u1 - u2 + u3 - u4) + Ixx*phi_dot_t*theta_dot_t*cos(theta_t)))/(Iyy*Izz*cos(phi(t))^4*cos(theta(t))^2 + Iyy*Izz*cos(theta(t))^2*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))^2*sin(phi(t))^2)
%                                                                                                                                                                                                                                           - ((Iyy*cos(phi(t))*sin(phi(t)) - Izz*cos(phi(t))*sin(phi(t)))*(psi_dot_t*(2*Izz*phi_dot_t*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Iyy*phi_dot_t*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Ixx*theta_dot_t*cos(theta_t)*sin(theta_t) + 2*Izz*theta_dot_t*cos(phi_t)^2*cos(theta_t)*sin(theta_t) + 2*Iyy*theta_dot_t*cos(theta_t)*sin(phi_t)^2*sin(theta_t)) - theta_dot_t*(Iyy*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Izz*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Iyy*phi_dot_t*cos(theta_t)*sin(phi_t)^2 + Izz*phi_dot_t*cos(theta_t)*sin(phi_t)^2 - Iyy*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t) + Izz*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t)) - b*(u1 - u2 + u3 - u4) + Ixx*phi_dot_t*theta_dot_t*cos(theta_t)))/(Iyy*Izz*cos(phi(t))^4*cos(theta(t)) + Iyy*Izz*cos(theta(t))*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))*sin(phi(t))^2) - ((Izz*cos(phi(t))^2 + Iyy*sin(phi(t))^2)*(theta_dot_t*((psi_dot_t*(Iyy*cos(phi_t)*sin(phi_t)*sin(theta_t) - Izz*cos(phi_t)*sin(phi_t)*sin(theta_t)))/2 - 2*Iyy*phi_dot_t*cos(phi_t)*sin(phi_t) + 2*Izz*phi_dot_t*cos(phi_t)*sin(phi_t)) + psi_dot_t*((theta_dot_t*(Iyy*cos(phi_t)*sin(phi_t)*sin(theta_t) - Izz*cos(phi_t)*sin(phi_t)*sin(theta_t)))/2 + (psi_dot_t*(2*Izz*cos(phi_t)^2*cos(theta_t)*sin(theta_t) - 2*Ixx*cos(theta_t)*sin(theta_t) + 2*Iyy*cos(theta_t)*sin(phi_t)^2*sin(theta_t)))/2 + (Ixx*phi_dot_t*cos(theta_t))/2 + Iyy*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Izz*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Iyy*phi_dot_t*cos(theta_t)*sin(phi_t)^2 + Izz*phi_dot_t*cos(theta_t)*sin(phi_t)^2 - Iyy*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t) + Izz*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t)) + k*l*(u1 - u3) + (Ixx*phi_dot_t*psi_dot_t*cos(theta_t))/2))/(Iyy*Izz*cos(phi(t))^4 + Iyy*Izz*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*sin(phi(t))^2) - (sin(theta(t))*(Iyy*cos(phi(t))*sin(phi(t)) - Izz*cos(phi(t))*sin(phi(t)))*(theta_dot_t*((psi_dot_t*(Iyy*cos(phi_t)^2*cos(theta_t) - Izz*cos(phi_t)^2*cos(theta_t) - Iyy*cos(theta_t)*sin(phi_t)^2 + Izz*cos(theta_t)*sin(phi_t)^2))/2 - (theta_dot_t*(2*Iyy*cos(phi_t)*sin(phi_t) - 2*Izz*cos(phi_t)*sin(phi_t)))/2) + psi_dot_t*((theta_dot_t*(Iyy*cos(phi_t)^2*cos(theta_t) - Izz*cos(phi_t)^2*cos(theta_t) - Iyy*cos(theta_t)*sin(phi_t)^2 + Izz*cos(theta_t)*sin(phi_t)^2))/2 + (psi_dot_t*(2*Iyy*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Izz*cos(phi_t)*cos(theta_t)^2*sin(phi_t)))/2 + Ixx*theta_dot_t*cos(theta_t)) - k*l*(u2 - u4)))/(Iyy*Izz*cos(phi(t))^4*cos(theta(t)) + Iyy*Izz*cos(theta(t))*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))*sin(phi(t))^2)
%                                                                                                                                                                                                           ((Iyy*cos(phi(t))*sin(phi(t)) - Izz*cos(phi(t))*sin(phi(t)))*(theta_dot_t*((psi_dot_t*(Iyy*cos(phi_t)*sin(phi_t)*sin(theta_t) - Izz*cos(phi_t)*sin(phi_t)*sin(theta_t)))/2 - 2*Iyy*phi_dot_t*cos(phi_t)*sin(phi_t) + 2*Izz*phi_dot_t*cos(phi_t)*sin(phi_t)) + psi_dot_t*((theta_dot_t*(Iyy*cos(phi_t)*sin(phi_t)*sin(theta_t) - Izz*cos(phi_t)*sin(phi_t)*sin(theta_t)))/2 + (psi_dot_t*(2*Izz*cos(phi_t)^2*cos(theta_t)*sin(theta_t) - 2*Ixx*cos(theta_t)*sin(theta_t) + 2*Iyy*cos(theta_t)*sin(phi_t)^2*sin(theta_t)))/2 + (Ixx*phi_dot_t*cos(theta_t))/2 + Iyy*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Izz*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Iyy*phi_dot_t*cos(theta_t)*sin(phi_t)^2 + Izz*phi_dot_t*cos(theta_t)*sin(phi_t)^2 - Iyy*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t) + Izz*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t)) + k*l*(u1 - u3) + (Ixx*phi_dot_t*psi_dot_t*cos(theta_t))/2))/(Iyy*Izz*cos(phi(t))^4*cos(theta(t)) + Iyy*Izz*cos(theta(t))*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))*sin(phi(t))^2) + ((Iyy*cos(phi(t))^2 + Izz*sin(phi(t))^2)*(psi_dot_t*(2*Izz*phi_dot_t*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Iyy*phi_dot_t*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Ixx*theta_dot_t*cos(theta_t)*sin(theta_t) + 2*Izz*theta_dot_t*cos(phi_t)^2*cos(theta_t)*sin(theta_t) + 2*Iyy*theta_dot_t*cos(theta_t)*sin(phi_t)^2*sin(theta_t)) - theta_dot_t*(Iyy*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Izz*phi_dot_t*cos(phi_t)^2*cos(theta_t) - Iyy*phi_dot_t*cos(theta_t)*sin(phi_t)^2 + Izz*phi_dot_t*cos(theta_t)*sin(phi_t)^2 - Iyy*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t) + Izz*theta_dot_t*cos(phi_t)*sin(phi_t)*sin(theta_t)) - b*(u1 - u2 + u3 - u4) + Ixx*phi_dot_t*theta_dot_t*cos(theta_t)))/(Iyy*Izz*cos(phi(t))^4*cos(theta(t))^2 + Iyy*Izz*cos(theta(t))^2*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))^2*sin(phi(t))^2) + (sin(theta(t))*(Iyy*cos(phi(t))^2 + Izz*sin(phi(t))^2)*(theta_dot_t*((psi_dot_t*(Iyy*cos(phi_t)^2*cos(theta_t) - Izz*cos(phi_t)^2*cos(theta_t) - Iyy*cos(theta_t)*sin(phi_t)^2 + Izz*cos(theta_t)*sin(phi_t)^2))/2 - (theta_dot_t*(2*Iyy*cos(phi_t)*sin(phi_t) - 2*Izz*cos(phi_t)*sin(phi_t)))/2) + psi_dot_t*((theta_dot_t*(Iyy*cos(phi_t)^2*cos(theta_t) - Izz*cos(phi_t)^2*cos(theta_t) - Iyy*cos(theta_t)*sin(phi_t)^2 + Izz*cos(theta_t)*sin(phi_t)^2))/2 + (psi_dot_t*(2*Iyy*cos(phi_t)*cos(theta_t)^2*sin(phi_t) - 2*Izz*cos(phi_t)*cos(theta_t)^2*sin(phi_t)))/2 + Ixx*theta_dot_t*cos(theta_t)) - k*l*(u2 - u4)))/(Iyy*Izz*cos(phi(t))^4*cos(theta(t))^2 + Iyy*Izz*cos(theta(t))^2*sin(phi(t))^4 + 2*Iyy*Izz*cos(phi(t))^2*cos(theta(t))^2*sin(phi(t))^2)
% 
